"""update projects table

Revision ID: 283df5ae5c34
Revises: 8a387dddc652
Create Date: 2025-10-24 15:23:50.584570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283df5ae5c34'
down_revision: Union[str, Sequence[str], None] = '8a387dddc652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('projects', sa.Column('lfs_allow', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('projects', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_favorite')
    op.drop_column('projects', 'lfs_allow')
    op.drop_column('projects', 'is_public')
    # ### end Alembic commands ###
