"""add timestamps to branches

Revision ID: 3561fc4eb6cf
Revises: 283df5ae5c34
Create Date: 2025-10-25 09:11:22.329913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3561fc4eb6cf'
down_revision: Union[str, Sequence[str], None] = '283df5ae5c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('branches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'created_at')
    op.drop_column('branches', 'updated_at')
    # ### end Alembic commands ###
