"""add aggregated tables

Revision ID: 41ffcd3b898b
Revises: 3561fc4eb6cf
Create Date: 2025-10-25 10:31:49.869484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ffcd3b898b'
down_revision: Union[str, Sequence[str], None] = '3561fc4eb6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agg_author_repo_day',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('commits', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_deleted', sa.Integer(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('msg_total_len', sa.Integer(), nullable=False),
    sa.Column('msg_short_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day', 'repo_id', 'author_id')
    )
    op.create_index('idx_ard_author_day', 'agg_author_repo_day', ['author_id', 'day'], unique=False)
    op.create_index('idx_ard_project_day', 'agg_author_repo_day', ['project_id', 'day'], unique=False)
    op.create_table('agg_file_repo_day',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('commits_touch', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_deleted', sa.Integer(), nullable=False),
    sa.Column('churn', sa.Integer(), nullable=False, comment='added+deleted'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day', 'repo_id', 'path')
    )
    op.create_index('idx_afrd_churn', 'agg_file_repo_day', ['repo_id', 'churn'], unique=False, postgresql_using='btree')
    op.create_index('idx_afrd_project_day', 'agg_file_repo_day', ['project_id', 'day'], unique=False)
    op.create_table('agg_hour_repo_day',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('hour', sa.SmallInteger(), nullable=False, comment='Hour of the day (0-23)'),
    sa.Column('commits', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_deleted', sa.Integer(), nullable=False),
    sa.CheckConstraint('hour >= 0 AND hour < 24', name='ck_agg_hour_valid_range'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day', 'repo_id', 'hour')
    )
    op.create_index('idx_ahrd_project_day', 'agg_hour_repo_day', ['project_id', 'day'], unique=False)
    op.create_table('agg_size_bucket_repo_day',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('bucket', sa.Enum('ZERO_TEN', 'ELEVEN_FIFTY', 'FIFTY_ONE_HUNDRED', 'HUNDRED_PLUS', name='size_bucket'), nullable=False),
    sa.Column('cnt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day', 'repo_id', 'bucket')
    )
    op.create_index('idx_asbrd_project_day', 'agg_size_bucket_repo_day', ['project_id', 'day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_asbrd_project_day', table_name='agg_size_bucket_repo_day')
    op.drop_table('agg_size_bucket_repo_day')
    op.drop_index('idx_ahrd_project_day', table_name='agg_hour_repo_day')
    op.drop_table('agg_hour_repo_day')
    op.drop_index('idx_afrd_project_day', table_name='agg_file_repo_day')
    op.drop_index('idx_afrd_churn', table_name='agg_file_repo_day', postgresql_using='btree')
    op.drop_table('agg_file_repo_day')
    op.drop_index('idx_ard_project_day', table_name='agg_author_repo_day')
    op.drop_index('idx_ard_author_day', table_name='agg_author_repo_day')
    op.drop_table('agg_author_repo_day')
    # ### end Alembic commands ###
