"""deprecate branch related fields

Revision ID: 678f5b6ec694
Revises: 96106954ea85
Create Date: 2025-10-24 12:42:34.922224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '678f5b6ec694'
down_revision: Union[str, Sequence[str], None] = '96106954ea85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('first_commit_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('authors', sa.Column('last_commit_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('branches', sa.Column('is_protected', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('branches_head_commit_sha_fkey'), 'branches', type_='foreignkey')
    op.drop_column('branches', 'head_commit_sha')
    op.add_column('commits', sa.Column('author_name', sa.String(), nullable=False))
    op.add_column('commits', sa.Column('author_email', sa.String(), nullable=False))
    op.add_column('commits', sa.Column('committer_name', sa.String(), nullable=True))
    op.add_column('commits', sa.Column('committer_email', sa.String(), nullable=True))
    op.add_column('commits', sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('commits', sa.Column('parents', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('commits', sa.Column('old_tag_names', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commits', 'old_tag_names')
    op.drop_column('commits', 'parents')
    op.drop_column('commits', 'issues')
    op.drop_column('commits', 'committer_email')
    op.drop_column('commits', 'committer_name')
    op.drop_column('commits', 'author_email')
    op.drop_column('commits', 'author_name')
    op.add_column('branches', sa.Column('head_commit_sha', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('branches_head_commit_sha_fkey'), 'branches', 'commits', ['head_commit_sha'], ['sha'], ondelete='SET NULL')
    op.drop_column('branches', 'is_protected')
    op.drop_column('authors', 'last_commit_at')
    op.drop_column('authors', 'first_commit_at')
    # ### end Alembic commands ###
