"""update commit_files, add new fields

Revision ID: 8a387dddc652
Revises: 678f5b6ec694
Create Date: 2025-10-24 12:52:23.523884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a387dddc652'
down_revision: Union[str, Sequence[str], None] = '678f5b6ec694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit_files', sa.Column('patch', sa.Text(), nullable=True))
    op.add_column('commit_files', sa.Column('is_binary', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commit_files', 'is_binary')
    op.drop_column('commit_files', 'patch')
    # ### end Alembic commands ###
