"""scm_integrations_unique

Revision ID: 9d91b30a4c8a
Revises: a8db239a7a81
Create Date: 2026-02-08 17:52:09.813488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d91b30a4c8a'
down_revision: Union[str, Sequence[str], None] = 'a8db239a7a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_scm_integrations_user_provider_external', 'scm_integrations', ['user_id', 'provider', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_scm_integrations_user_provider_external', 'scm_integrations', type_='unique')
    # ### end Alembic commands ###
