"""add_scm_integrations_and_project_provider

Revision ID: a8db239a7a81
Revises: 41ffcd3b898b
Create Date: 2026-02-08 17:44:37.347594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8db239a7a81'
down_revision: Union[str, Sequence[str], None] = '41ffcd3b898b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scm_integrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True, comment='Provider user id (as string to avoid int size issues across providers)'),
    sa.Column('external_login', sa.String(), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scm_integrations_user_id'), 'scm_integrations', ['user_id'], unique=False)
    op.add_column('projects', sa.Column('provider', sa.String(), server_default='sfera', nullable=False, comment='SCM provider slug (sfera/github/gitlab/...)'))
    op.add_column('projects', sa.Column('external_id', sa.BigInteger(), nullable=True, comment='Provider native project/group/org id'))
    op.add_column('projects', sa.Column('integration_id', sa.Uuid(), nullable=True, comment='Which OAuth integration this project was synced from'))
    op.drop_constraint(op.f('projects_name_key'), 'projects', type_='unique')
    op.create_unique_constraint('uq_projects_provider_external_id', 'projects', ['provider', 'external_id'])
    op.create_unique_constraint('uq_projects_provider_name', 'projects', ['provider', 'name'])
    op.create_foreign_key(None, 'projects', 'scm_integrations', ['integration_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint('uq_projects_provider_name', 'projects', type_='unique')
    op.drop_constraint('uq_projects_provider_external_id', 'projects', type_='unique')
    op.create_unique_constraint(op.f('projects_name_key'), 'projects', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'integration_id')
    op.drop_column('projects', 'external_id')
    op.drop_column('projects', 'provider')
    op.drop_index(op.f('ix_scm_integrations_user_id'), table_name='scm_integrations')
    op.drop_table('scm_integrations')
    # ### end Alembic commands ###
